// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace PlatformManagement.Models.EFModels;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeRoleRel> EmployeeRoleRels { get; set; }

    public virtual DbSet<Function> Functions { get; set; }

    public virtual DbSet<GroupBuying> GroupBuyings { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoleFunctionRel> RoleFunctionRels { get; set; }

    public virtual DbSet<Shop> Shops { get; set; }

    public virtual DbSet<Wish> Wishes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cart>(entity =>
        {
            entity.Property(e => e.Quantity).HasComment("數量");

            entity.HasOne(d => d.GroupBuying).WithMany(p => p.Carts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Carts_GroupBuyings");

            entity.HasOne(d => d.Member).WithMany(p => p.Carts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Carts_Members");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.Property(e => e.DisplayOrder).HasComment("顯示順序");
            entity.Property(e => e.Enabled).HasComment("是否啟用");
            entity.Property(e => e.Name).HasComment("分類名稱");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.Property(e => e.Account).HasComment("帳號");
            entity.Property(e => e.EncryptedPassword).HasComment("加密後密碼");
            entity.Property(e => e.Name).HasComment("姓名");
        });

        modelBuilder.Entity<EmployeeRoleRel>(entity =>
        {
            entity.HasOne(d => d.Employee).WithMany(p => p.EmployeeRoleRels)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Employee_Role_Rel_Employees");

            entity.HasOne(d => d.Role).WithMany(p => p.EmployeeRoleRels)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Employee_Role_Rel_Roles");
        });

        modelBuilder.Entity<Function>(entity =>
        {
            entity.Property(e => e.Name).HasComment("功能名稱");
        });

        modelBuilder.Entity<GroupBuying>(entity =>
        {
            entity.Property(e => e.Description).HasComment("團購說明");
            entity.Property(e => e.Enabled).HasComment("是否上架");
            entity.Property(e => e.EndDate).HasComment("結束時間");
            entity.Property(e => e.MinimumGroupSize).HasComment("最小成團人數");
            entity.Property(e => e.Price).HasComment("團購價格");
            entity.Property(e => e.StartDate).HasComment("開始時間");

            entity.HasOne(d => d.Product).WithMany(p => p.GroupBuyings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_GroupBuyings_Products");
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.Property(e => e.Account).HasComment("帳號");
            entity.Property(e => e.Birthday).HasComment("生日");
            entity.Property(e => e.ConfirmCode).HasComment("驗證碼");
            entity.Property(e => e.Email).HasComment("電子信箱");
            entity.Property(e => e.EncryptedPassword).HasComment("加密後密碼");
            entity.Property(e => e.Gender).HasComment("性別(0:女,1:男)");
            entity.Property(e => e.IsConfirmed).HasComment("是否通過驗證");
            entity.Property(e => e.Name).HasComment("姓名");
            entity.Property(e => e.Phone)
                .IsFixedLength()
                .HasComment("手機號碼");
            entity.Property(e => e.Status).HasComment("狀態(0:停用,1:啟用)");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.Property(e => e.DeliveryStatus).HasComment("運送狀態(0: 未出貨, 1: 已送達)");
            entity.Property(e => e.PaymentStatus).HasComment("付款狀態(0:未付款,1:已付款)");
            entity.Property(e => e.Price).HasComment("成交價格");
            entity.Property(e => e.Quantity).HasComment("數量");
            entity.Property(e => e.ShippingAddress).HasComment("運送地址");
            entity.Property(e => e.ShippingMethod).HasComment("運送方式(1:到店取)");
            entity.Property(e => e.Status).HasComment("訂單狀態(0: 取消, 1: 參與中, 2: 成立, 3: 運送中, 4: 到貨, 5: 已取貨, 6: 未取貨)");

            entity.HasOne(d => d.GroupBuying).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_GroupBuyings");

            entity.HasOne(d => d.Member).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Members");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.Property(e => e.Info).HasComment("商品資訊");
            entity.Property(e => e.Name).HasComment("商品名稱");
            entity.Property(e => e.Price).HasComment("原價");

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Categories");

            entity.HasOne(d => d.Shop).WithMany(p => p.Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Products_Shops");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.Property(e => e.Path).HasComment("圖片路徑");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ProductImages_Products");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.Property(e => e.Name).HasComment("角色名稱");
        });

        modelBuilder.Entity<RoleFunctionRel>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            entity.HasOne(d => d.Function).WithMany(p => p.RoleFunctionRels)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Role_Function_Rel_Functions");

            entity.HasOne(d => d.IdNavigation).WithOne(p => p.RoleFunctionRel)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Role_Function_Rel_Roles");
        });

        modelBuilder.Entity<Shop>(entity =>
        {
            entity.Property(e => e.Account).HasComment("帳號");
            entity.Property(e => e.Address).HasComment("商店地址");
            entity.Property(e => e.Avatar).HasComment("頭像");
            entity.Property(e => e.EncryptedPassword).HasComment("加密後密碼");
            entity.Property(e => e.IdentityCard)
                .IsFixedLength()
                .HasComment("身分證字號");
            entity.Property(e => e.Name).HasComment("商店名稱");
            entity.Property(e => e.Status).HasComment("狀態(0:停用,1:啟用)");
        });

        modelBuilder.Entity<Wish>(entity =>
        {
            entity.HasOne(d => d.Member).WithMany(p => p.Wishes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wishes_Members");

            entity.HasOne(d => d.Product).WithMany(p => p.Wishes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Wishes_Products");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}