// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlatformManagement.Models.EFModels;

[Table("Employee_Role_Rel")]
public partial class EmployeeRoleRel
{
    [Key]
    public int Id { get; set; }

    public int EmployeeId { get; set; }

    public int RoleId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeRoleRels")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("RoleId")]
    [InverseProperty("EmployeeRoleRels")]
    public virtual Role Role { get; set; }
}