// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlatformManagement.Models.EFModels;

public partial class Employee
{
    [Key]
    public int Id { get; set; }

    public int PositionId { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Account { get; set; }

    /// <summary>
    /// 加密後密碼
    /// </summary>
    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string EncryptedPassword { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    [Required]
    [StringLength(5)]
    public string Name { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<EmployeeRoleRel> EmployeeRoleRels { get; set; } = new List<EmployeeRoleRel>();
}