// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlatformManagement.Models.EFModels;

public partial class GroupBuying
{
    [Key]
    public int Id { get; set; }

    public int ProductId { get; set; }

    /// <summary>
    /// 團購價格
    /// </summary>
    public int Price { get; set; }

    /// <summary>
    /// 最小成團人數
    /// </summary>
    public int MinimumGroupSize { get; set; }

    /// <summary>
    /// 團購說明
    /// </summary>
    [StringLength(1000)]
    public string Description { get; set; }

    /// <summary>
    /// 開始時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime StartDate { get; set; }

    /// <summary>
    /// 結束時間
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime EndDate { get; set; }

    /// <summary>
    /// 是否上架
    /// </summary>
    public bool Enabled { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("GroupBuying")]
    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    [InverseProperty("GroupBuying")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [ForeignKey("ProductId")]
    [InverseProperty("GroupBuyings")]
    public virtual Product Product { get; set; }
}