// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlatformManagement.Models.EFModels;

public partial class Member
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Account { get; set; }

    /// <summary>
    /// 加密後密碼
    /// </summary>
    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string EncryptedPassword { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    [Required]
    [StringLength(5)]
    public string Name { get; set; }

    /// <summary>
    /// 性別(0:女,1:男)
    /// </summary>
    public byte? Gender { get; set; }

    /// <summary>
    /// 電子信箱
    /// </summary>
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    /// <summary>
    /// 手機號碼
    /// </summary>
    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string Phone { get; set; }

    /// <summary>
    /// 生日
    /// </summary>
    [Column(TypeName = "datetime")]
    public DateTime? Birthday { get; set; }

    /// <summary>
    /// 狀態(0:停用,1:啟用)
    /// </summary>
    public short Status { get; set; }

    /// <summary>
    /// 是否通過驗證
    /// </summary>
    public bool IsConfirmed { get; set; }

    /// <summary>
    /// 驗證碼
    /// </summary>
    [StringLength(50)]
    [Unicode(false)]
    public string ConfirmCode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    [InverseProperty("Member")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [InverseProperty("Member")]
    public virtual ICollection<Wish> Wishes { get; set; } = new List<Wish>();
}