// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlatformManagement.Models.EFModels;

public partial class Product
{
    [Key]
    public int Id { get; set; }

    public int ShopId { get; set; }

    public int CategoryId { get; set; }

    /// <summary>
    /// 商品名稱
    /// </summary>
    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    /// <summary>
    /// 原價
    /// </summary>
    public int Price { get; set; }

    /// <summary>
    /// 商品資訊
    /// </summary>
    [StringLength(3000)]
    public string Info { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("Products")]
    public virtual Category Category { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<GroupBuying> GroupBuyings { get; set; } = new List<GroupBuying>();

    [InverseProperty("Product")]
    public virtual ICollection<ProductImage> ProductImages { get; set; } = new List<ProductImage>();

    [ForeignKey("ShopId")]
    [InverseProperty("Products")]
    public virtual Shop Shop { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<Wish> Wishes { get; set; } = new List<Wish>();
}