// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlatformManagement.Models.EFModels;

public partial class Shop
{
    [Key]
    public int Id { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Account { get; set; }

    /// <summary>
    /// 加密後密碼
    /// </summary>
    [Required]
    [StringLength(256)]
    [Unicode(false)]
    public string EncryptedPassword { get; set; }

    /// <summary>
    /// 商店名稱
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    [StringLength(10)]
    [Unicode(false)]
    public string IdentityCard { get; set; }

    /// <summary>
    /// 頭像
    /// </summary>
    [StringLength(500)]
    public string Avatar { get; set; }

    /// <summary>
    /// 商店地址
    /// </summary>
    [StringLength(150)]
    public string Address { get; set; }

    /// <summary>
    /// 狀態(0:停用,1:啟用)
    /// </summary>
    public short Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [InverseProperty("Shop")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}