// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PlatformManagement.Models.EFModels;

public partial class Wish
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int ProductId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime UpdatedAt { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("Wishes")]
    public virtual Member Member { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Wishes")]
    public virtual Product Product { get; set; }
}