// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forestage.Models.EFModels;

public partial class Cart
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int GroupBuyingId { get; set; }

    /// <summary>
    /// 數量
    /// </summary>
    public int Quantity { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual GroupBuying GroupBuying { get; set; }

    public virtual Member Member { get; set; }
}