// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forestage.Models.EFModels;

public partial class Employee
{
    public int Id { get; set; }

    public int PositionId { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 加密後密碼
    /// </summary>
    public string EncryptedPassword { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<EmployeeRoleRel> EmployeeRoleRels { get; set; } = new List<EmployeeRoleRel>();
}