// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forestage.Models.EFModels;

public partial class Function
{
    public int Id { get; set; }

    /// <summary>
    /// 功能名稱
    /// </summary>
    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<RoleFunctionRel> RoleFunctionRels { get; set; } = new List<RoleFunctionRel>();
}