// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forestage.Models.EFModels;

public partial class GroupBuying
{
    public int Id { get; set; }

    public int ProductId { get; set; }

    /// <summary>
    /// 團購價格
    /// </summary>
    public int Price { get; set; }

    /// <summary>
    /// 最小成團人數
    /// </summary>
    public int MinimumGroupSize { get; set; }

    /// <summary>
    /// 團購說明
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// 開始時間
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// 結束時間
    /// </summary>
    public DateTime EndDate { get; set; }

    /// <summary>
    /// 是否上架
    /// </summary>
    public bool Enabled { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Product Product { get; set; }
}