// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forestage.Models.EFModels;

public partial class Member
{
    public int Id { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 加密後密碼
    /// </summary>
    public string EncryptedPassword { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 性別(0:女,1:男)
    /// </summary>
    public byte? Gender { get; set; }

    /// <summary>
    /// 電子信箱
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 手機號碼
    /// </summary>
    public string Phone { get; set; }

    /// <summary>
    /// 生日
    /// </summary>
    public DateTime? Birthday { get; set; }

    /// <summary>
    /// 狀態(0:停用,1:啟用)
    /// </summary>
    public short Status { get; set; }

    /// <summary>
    /// 是否通過驗證
    /// </summary>
    public bool IsConfirmed { get; set; }

    /// <summary>
    /// 驗證碼
    /// </summary>
    public string ConfirmCode { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Cart> Carts { get; set; } = new List<Cart>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Wish> Wishes { get; set; } = new List<Wish>();
}