// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forestage.Models.EFModels;

public partial class Order
{
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int GroupBuyingId { get; set; }

    /// <summary>
    /// 成交價格
    /// </summary>
    public int Price { get; set; }

    /// <summary>
    /// 數量
    /// </summary>
    public int Quantity { get; set; }

    /// <summary>
    /// 運送方式(1:超商,2:宅配)
    /// </summary>
    public short ShippingMethod { get; set; }

    /// <summary>
    /// 運送地址
    /// </summary>
    public string ShippingAddress { get; set; }

    /// <summary>
    /// 訂單狀態(0:已取消,1:處理中,2:已完成)
    /// </summary>
    public short Status { get; set; }

    /// <summary>
    /// 付款狀態(0:未付款,1:已付款)
    /// </summary>
    public short PaymentStatus { get; set; }

    /// <summary>
    /// 運送狀態(0:未出貨,1:已出貨,2:已送達)
    /// </summary>
    public short DeliveryStatus { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual GroupBuying GroupBuying { get; set; }

    public virtual Member Member { get; set; }
}