// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forestage.Models.EFModels;

public partial class RoleFunctionRel
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public int FunctionId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Function Function { get; set; }

    public virtual Role IdNavigation { get; set; }
}