// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forestage.Models.EFModels;

public partial class Role
{
    public int Id { get; set; }

    /// <summary>
    /// 角色名稱
    /// </summary>
    public string Name { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<EmployeeRoleRel> EmployeeRoleRels { get; set; } = new List<EmployeeRoleRel>();

    public virtual RoleFunctionRel RoleFunctionRel { get; set; }
}