// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Forestage.Models.EFModels;

public partial class Shop
{
    public int Id { get; set; }

    /// <summary>
    /// 帳號
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 加密後密碼
    /// </summary>
    public string EncryptedPassword { get; set; }

    /// <summary>
    /// 商店名稱
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string IdentityCard { get; set; }

    /// <summary>
    /// 頭像
    /// </summary>
    public string Avatar { get; set; }

    /// <summary>
    /// 商店地址
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// 狀態(0:停用,1:啟用)
    /// </summary>
    public short Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}